import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pluginDir = path.join(rootDir, 'plugin');
const outDir = path.join(pluginDir, 'dist');
const corePath = path.join(rootDir, 'packages', 'figma-plugin-core', 'src', 'index.mjs');
const pluginPath = path.join(pluginDir, 'src', 'code.mjs');

fs.mkdirSync(outDir, { recursive: true });

let core = fs.readFileSync(corePath, 'utf8')
  .replace(/^export\s+/gm, '');
let plugin = fs.readFileSync(pluginPath, 'utf8')
  .replace(/import\s*\{[\s\S]*?\}\s*from\s*['"]\.\.\/\.\.\/packages\/figma-plugin-core\/src\/index\.mjs['"];?\s*/m, '');

const banner = `// Generated by tools/build-plugin.mjs. Do not edit dist directly.\n`;
fs.writeFileSync(path.join(outDir, 'code.js'), `${banner}${core}\n${plugin}`, 'utf8');
fs.copyFileSync(path.join(pluginDir, 'src', 'ui.html'), path.join(outDir, 'ui.html'));
console.log('Figma plugin built: plugin/dist/code.js + plugin/dist/ui.html');
